In [1]:
%load_ext autoreload

# Examen

## Determinante

In [6]:
%autoreload 2
from src import (
    eliminacion_gaussiana,
    descomposicion_LU,
    resolver_LU,
    matriz_aumentada,
    separar_m_aumentada,
)


# lISTA DE CAMBIOS

# 1. Determinante.ipynb
# calc_determinante: Calcula el determinante usando descomposición LU, multiplicando los elementos diagonales de U.

# 2. src
# eliminacion_gaussiana: Resuelve sistemas de ecuaciones lineales mediante eliminación gaussiana con pivoteo.
#descomposicion_LU: Realiza la descomposición LU con pivoteo parcial.
#resolver_LU: Resuelve sistemas de ecuaciones utilizando la descomposición LU.
#matriz_aumentada: Construye la matriz aumentada de un sistema de ecuaciones.
#separar_m_aumentada: Separa la matriz aumentada en la matriz de coeficientes y el vector independiente.

# 3.Se añade manejo de excepciones y logging.
#Se asegura el pivoteo parcial en la descomposición LU.

# ####################################################################
def calc_determinante(A: list[list[float]]) -> float:
    """Función que calcula el determinante usando el método de descomposición LU.

    ## Parameters
    ``A``: Matriz cuadrada de tamaño n x n

    ## Return
    ``detA``: Determinante de la matriz A
    """
    import numpy as np

    A = np.array(A, dtype=float)
    try:
        L, U = descomposicion_LU(A)  # Descomposición LU
        detA = np.prod(np.diag(U))  # Producto de los elementos diagonales de U
    except ValueError as e:
        detA = 0  # Determinante es 0 si no hay solución única
    return detA


# Ejercicio 1

In [3]:
A1 = [
    [-4, 2, -4, -4, 1, 2, 5, 3, 5, 1],
    [1, 0, 4, 3, 0, -2, 3, 0, 1, 5],
    [5, 5, -4, 5, -4, 2, 2, 2, 4, 4],
    [-1, 3, 4, -1, -4, 0, 5, 0, 0, 5],
    [4, 1, 4, 2, 0, 0, 3, -1, 0, 2],
    [2, -2, 1, -1, -2, -3, 2, -2, 4, -1],
    [3, -2, -3, -2, -1, -3, 5, -1, 5, 0],
    [3, 4, -3, 3, -2, 2, -4, -4, 1, 5],
    [-4, 0, 3, 3, -3, -2, -2, 0, 5, -4],
    [-2, 4, 4, -2, -1, 1, 5, -1, 3, -3],
]
calc_determinante(A1)

[01-11 13:13:14][INFO] 
[[-4.    2.   -4.   -4.    1.    2.    5.    3.    5.    1.  ]
 [ 0.    0.5   3.    2.    0.25 -1.5   4.25  0.75  2.25  5.25]
 [ 0.    7.5  -9.    0.   -2.75  4.5   8.25  5.75 10.25  5.25]
 [ 0.    2.5   5.    0.   -4.25 -0.5   3.75 -0.75 -1.25  4.75]
 [ 0.    3.    0.   -2.    1.    2.    8.    2.    5.    3.  ]
 [ 0.   -1.   -1.   -3.   -1.5  -2.    4.5  -0.5   6.5  -0.5 ]
 [ 0.   -0.5  -6.   -5.   -0.25 -1.5   8.75  1.25  8.75  0.75]
 [ 0.    5.5  -6.    0.   -1.25  3.5  -0.25 -1.75  4.75  5.75]
 [ 0.   -2.    7.    7.   -4.   -4.   -7.   -3.    0.   -5.  ]
 [ 0.    3.    6.    0.   -1.5   0.    2.5  -2.5   0.5  -3.5 ]]
[01-11 13:13:14][INFO] 
[[ -4.     2.    -4.    -4.     1.     2.     5.     3.     5.     1.  ]
 [  0.     0.5    3.     2.     0.25  -1.5    4.25   0.75   2.25   5.25]
 [  0.     0.   -54.   -30.    -6.5   27.   -55.5   -5.5  -23.5  -73.5 ]
 [  0.     0.   -10.   -10.    -5.5    7.   -17.5   -4.5  -12.5  -21.5 ]
 [  0.     0.   -18.   -14.  

9912776.000000015

# Ejercicio 2

In [4]:
A2 = [
    [2, 2, 4, 5, -2, -3, 2, -2],
    [-1, -1, 3, 2, 1, 1, -4, 4],
    [2, 5, -3, -3, -2, 2, 5, 3],
    [-2, -4, 0, 1, -1, 5, -4, -1],
    [1, -2, -1, 5, 5, 2, 1, -2],
    [5, 4, 0, 3, 4, -1, -3, -2],
    [4, -4, 1, 2, 3, 3, -1, 3],
    [-2, 1, -3, 0, 5, 4, 4, -4],
]
calc_determinante(A2)

[01-11 13:13:14][INFO] 
[[  2.    2.    4.    5.   -2.   -3.    2.   -2. ]
 [  0.    0.    5.    4.5   0.   -0.5  -3.    3. ]
 [  0.    3.   -7.   -8.    0.    5.    3.    5. ]
 [  0.   -2.    4.    6.   -3.    2.   -2.   -3. ]
 [  0.   -3.   -3.    2.5   6.    3.5   0.   -1. ]
 [  0.   -1.  -10.   -9.5   9.    6.5  -8.    3. ]
 [  0.   -8.   -7.   -8.    7.    9.   -5.    7. ]
 [  0.    3.    1.    5.    3.    1.    6.   -6. ]]
[01-11 13:13:14][INFO] 
[[  2.      2.      4.      5.     -2.     -3.      2.     -2.   ]
 [  0.     -8.     -7.     -8.      7.      9.     -5.      7.   ]
 [  0.      0.     -9.625 -11.      2.625   8.375   1.125   7.625]
 [  0.      0.      5.75    8.     -4.75   -0.25   -0.75   -4.75 ]
 [  0.      0.     -0.375   5.5     3.375   0.125   1.875  -3.625]
 [  0.      0.     -9.125  -8.5     8.125   5.375  -7.375   2.125]
 [  0.      0.      5.      4.5     0.     -0.5    -3.      3.   ]
 [  0.      0.     -1.625   2.      5.625   4.375   4.125  -3.375]]
[01-11

-2341545.9999999986